show databases;
create database customer_behaviour;
use customer_behaviour;
select * from customer limit 20;
select * from customer;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
where discount_applied='Yes' and purchase_amount >= ( select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as rating from customer
group by item_purchased 
order by rating desc
limit 5

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as averages from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,round(avg(purchase_amount),2) as spending ,round(sum(purchase_amount),2) as revenue, count(customer_id) as count from customer
where subscription_status in ('Yes','No')
group by subscription_status
order by revenue,spending;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with ctype as(
select customer_id,previous_purchases,
case 
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of customers"
from ctype
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
select category,item_purchased, total_orders
from (
	select category,item_purchased, count(previous_purchases) as total_orders,
    rank() over (partition by category order by count(previous_purchases)desc) as product_rank
from customer 
group by category,item_purchased
) as ranked_products
where product_rank<=3
order by category,total_orders desc;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where (previous_purchases)>5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as revenue
from customer 
group by age_group
order by revenue desc

select * from customer;